# API for initializing the database with seed data
GET http://localhost:3013/

# API for statistics of the selected month
GET http://localhost:3013/api/statistics/7

# API for bar chart data of the selected month
GET http://localhost:3013/api/bar-chart/9

# API for pie chart data of the selected month
GET http://localhost:3013/api/pie-chart/7

